- name: create folder for guest_images
  file:
    path: /home/stack/guest_images
    state: directory
    owner: stack
    group: stack
    mode: 0775
  tags: post-overcloud

- debug:
    var: overcloud_guest_images

- name: prompt user to make sure guest images are in place
  pause:
    prompt:
      'Please make sure that guest images defined in your vars.yml (above) are in hattrick/guest_images/ on your Ansible host. Press return to continue. Press Ctrl+c and then "a" to abort'

- name: copy guest_images to Undercloud
  copy:
    src: guest_images/
    dest: /home/stack/guest_images
  tags: post-overcloud

#TODO: Need to convert this script to ansible tasks
- name: copy overcloud post config script
  become: yes
  become_user: stack
  template:
    src: "templates/overcloudPostConfig.sh.j2"
    dest: /home/stack/overcloudPostConfig.sh
    owner: stack
    group: stack
    mode: 0775
  tags: post-overcloud

- name: run overcloud post configuration
  become: yes
  become_user: stack
  shell: |
    /home/stack/overcloudPostConfig.sh \
    > /home/stack/overcloud-post-deploy.log 2>&1
  args:
    chdir: /home/stack
  #async: 300
  #poll: 10
  tags: post-overcloud
  ignore_errors: true #TODO: Remove later
