heat_template_version: 2014-10-16

description: >
 Configure Nested Virtualization on Nova Compute Node
parameters:
  servers:
    type: json

resources:
  NestedVirtConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: /home/stack/templates/nested-virt-config.py}

  NestedVirtDeployments:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers: {get_param: servers}
      config: {get_resource: NestedVirtConfig}
      actions: ['CREATE', 'UPDATE']
