---

- name: Create volume(s)
  os_volume:
    display_name: "{{ osp_instance_name }}-{{ item.name }}"
    size: "{{ item.size }}"
    state: present
    auth: "{{ os_auth }}"
  with_items: "{{ osp_instance_volumes }}"
  register: osp_create_volumes

- debug:
    var: osp_instance_create_volumes

- name: Launch instance
  os_server:
    name: "{{ osp_instance_name }}"
    image: "{{ osp_instance_image }}"
    flavor: "{{ osp_instance_flavor }}"
    key_name: "{{ osp_instance_key_name }}"
    security_groups: "{{ osp_instance_security_groups }}"
    volumes: "{{ osp_create_volumes.results | map(attribute='volume.display_name') | list }}"
    auto_ip: "{{ osposp_instance_auto_ip_auto_ip }}"
    timeout: "{{ osp_instance_timeout | default(300) }}"
  register: osp_instance_launch

- debug:
    var: osp_instance_launch
