---

all:
  hosts:
    localhost:
      ansible_python_interpreter: /usr/bin/python
      ansible_connection: local
    kvm:
      ansible_host: "{{ kvm_public_ip }}"
      ansible_ssh_user: "{{ kvm_ssh_user }}"
      ansible_ssh_pass: "{{ kvm_ssh_pass }}"
    idm:
      ansible_host: "{{ idm_public_ip }}"
      ansible_ssh_user: "{{ kvm_ssh_user }}"
      ansible_ssh_pass: "{{ kvm_ssh_pass }}"
    content:
      ansible_host: "{{ content_public_ip }}"
      ansible_ssh_user: "{{ kvm_ssh_user }}"
      ansible_ssh_pass: "{{ kvm_ssh_pass }}"
    director:
      ansible_host: "{{ director_public_ip }}"
      ansible_ssh_user: "{{ kvm_ssh_user }}"
      ansible_ssh_pass: "{{ kvm_ssh_pass }}"
