---

all:
  hosts:
    localhost:
      ansible_python_interpreter: python
      ansible_connection: local
    kvm:
      ansible_host: "{{ kvm_public_ip }}"
      #ansible_ssh_user: "{{ kvm_ssh_user }}"
      ansible_ssh_user: kejones
      ansible_ssh_pass: "{{ kvm_ssh_pwd }}"
    idm:
      ansible_host: "{{ idm_public_ip }}"
      ansible_ssh_user: "{{ idm_ssh_user }}"
      ansible_ssh_pass: "{{ idm_ssh_pwd }}"
    content:
      ansible_host: "{{ content_public_ip }}"
      ansible_ssh_user: "{{ content_ssh_user }}"
      ansible_ssh_pass: "{{ content_ssh_pwd }}"
    director:
      ansible_host: "{{ director_public_ip }}"
      ansible_ssh_user: "{{ director_ssh_user }}"
      ansible_ssh_pass: "{{ director_ssh_pwd }}"
    tower:
      ansible_host: "{{ tower_public_ip }}"
      ansible_ssh_user: "cloud-user"
