---

- name: Unregister host from RHSM
  redhat_subscription:
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    state: absent
  become: yes

- name: Subscription-manager clean all
  command: subscription-manager clean
