- name: Add keypair with current user public key
  tags: provision
  os_keypair:
    auth: "{{ os_auth }}"
    state: present
    name: "{{ os_instance_key_name }}"
    public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"


- name: Create Tower instance
  tags: provision
  include_role:
    name: openstack_instance
  vars:
    os_instance_floating_ip: 192.168.1.80
    #os_instance_auto_ip: no
    os_instance_terminate_volume: yes
    os_instance_security_groups:
      - name: ssh
        description: Allow SSH
        rules:
          - protocol: tcp
            port_range_min: 22
            port_range_max: 22
            remote_ip_prefix: 0.0.0.0/0
      - name: web
        rules:
          - protocol: tcp
            port_range_min: 80
            port_range_max: 80
            remote_ip_prefix: 0.0.0.0/0
          - protocol: tcp
            port_range_min: 443
            port_range_max: 443
            remote_ip_prefix: 0.0.0.0/0

#- name: Assign floating IP to Tower
#  tags: provision
#  os_floating_ip:
#    auth: "{{ os_auth }}"
#    state: present
#    server: "{{ tower_hostname }}.{{ domain }}"
#    floating_ip_address: "{{ tower_public_ip }}"
#    network: public
#    wait: true

- name: Wait for instance become ready to use
  tags: provision
  wait_for:
   host: "{{ tower_public_ip }}"
   port: "22"
   timeout: "320"
   state: "started"

- name: Pause playbook execution for 30 seconds
  tags: provision
  pause:
    seconds: 30
