---
# tasks file for idm
- name: set hostname
  hostname:
    name: "{{ idm_hostname }}.{{ domain }}"

- name: add line to hosts file for self
  lineinfile:
    dest: /etc/hosts
    state: present
    regexp: "^{{ idm_public_ip }}"
    line: "{{ idm_public_ip }} {{ idm_hostname }}.{{ domain }} {{ idm_hostname }}"

- name: update packages
  yum:
    name: '*'
    state: latest
  register: yum_result
  async: 1000
  poll: 30

- name: check Kernel is the Latest
  shell: if [ $(uname -r) == $(rpm -q kernel | tail -n 1 | sed -e 's/kernel-//g') ] ; then echo no ; else echo reboot; fi
  ignore_errors: true
  register: reboot_hint

- name: install IPA packages
  yum:
    name: "{{ idm_packages }}"
    state: latest

- name: restart server to get updated kernel
  shell: sleep 2 && shutdown -r now "Ansible restart triggered for latest kernel"
  async: 1
  poll: 0
  ignore_errors: true
  when: yum_result.changed or reboot_hint.stdout.find("reboot") != -1

- name: waiting for IDM server to come back online
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

- name: Set up IPA Server
  command: ipa-server-install -Uq -r '{{ idm_realm }}' -n '{{ domain }}' --allow-zone-overlap -p '{{ idm_dm_pwd }}' -a '{{ idm_admin_pwd }}' --setup-dns --auto-reverse --reverse-zone '{{ idm_reverse_zone }}' --forwarder '{{ idm_forward_ip }}'
  when: idm_forward_ip is defined

- name: Set up IPA Server (without DNS forwarding)
  command: ipa-server-install -Uq -r '{{ idm_realm }}' -n '{{ domain }}' --allow-zone-overlap -p '{{ idm_dm_pwd }}' -a '{{ idm_admin_pwd }}' --setup-dns --auto-reverse --reverse-zone '{{ idm_reverse_zone }}' --no-forwarders
  when: idm_forward_ip is not defined

- name: waiting for IDM services to come up
  wait_for:
    host: "{{ idm_public_ip }}"
    port: 443
    state: started
    delay: 10
    connect_timeout: 300
    sleep: 5

- name: disable dns forwarding on IDM server for disconnected install
  shell: "echo '{{ idm_admin_pwd }}' | kinit admin && ipa dnsserver-mod --forward-policy=none {{ idm_hostname }}.{{ domain }}"
  ignore_errors: true
  when: idm_forward_ip is not defined

- name: enable dynamic updates on dns zones
  command: "echo {{ idm_admin_pwd }} | kinit admin && ipa dnszone-mod {{ item }} --dynamic-update=TRUE"
  with_items:
    - "{{ domain }}"
    - "{{ idm_reverse_zone}}"

- name: enable allow ptr sync on dns zones
  command: "echo {{ idm_admin_pwd }} | kinit admin && ipa dnszone-mod --allow-sync-ptr=1 {{ item }}"
  with_items:
    - "{{ domain }}"
    - "{{ idm_reverse_zone}}"

- name: remove temporary nameserver from /etc/resolv.conf file
  lineinfile:
    dest: /etc/resolv.conf
    line: "nameserver {{ dns_server_public }}"
    state: absent
