---
# defaults file for roles/kvm
kvm_hostname_full: kvm.example.com
kvm_disks:
  root: sda
  #libvirt_images: sdb
  #destructive_filesystem: true
kvm_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-rh-common-rpms
kvm_packages:
  - 'screen'
  - 'wget'
  - 'vim'
  - 'tree'
  - 'yum-utils'
  - 'git'
  - 'qemu-kvm'
  - 'qemu-img'
  - 'libvirt'
  - 'virt-install'
  - 'libvirt-client'
  - 'libvirt-python'
  - 'libguestfs-tools-c'
  - 'rhel-guest-image-7'
  - 'ansible'
