---
- hosts: localhost
  connection: local
  name: Play that sets up a linux system to host the hattrick repo for execution
  tasks:
    #NOTE: RHEL 7 systems must be subscribed and have the following repos enabled
    #      - rhel-7-server-rpms
    #      - rhel-7-server-extras-rpms
    #      - rhel-7-server-optional-rpms
    #      - rhel-7-server-ansible-2.9-rpms
    #
    #      RHEL 8 systems must be subscribed and have the following repos enabled
    #      - rhel-8-for-x86_64-baseos-rpms
    #      - rhel-8-for-x86_64-appstream-rpms
    #      - ansible-2.9-for-rhel-8-x86_64-rpms

    - name: install packages
      become: yes
      package:
        name:
          - tmux
          - python3-pip
          - git
          - gcc
          - libcurl-devel
          - libxml2-devel
          - openssl-devel
          - python3-devel
        state: present

    - name: install python36 on Fedora systems
      become: yes
      package:
        name: python36
        state: present
      when: ansible_distribution == "Fedora"

    - name: install pipenv
      pip:
        name: pipenv
        executable: pip3
        extra_args: --user

    - name: clone the repository
      git:
        repo: https://github.com/RedHatGov/hattrick.git
        dest: hattrick
        force: yes

    - name: make sure pipenv is in path
      lineinfile:
        path: .bash_profile
        state: present
        regexp: '^PATH='
        line: 'PATH=$PATH:$HOME/.local/bin:$HOME/bin'

    - name: run pipenv install to get all dependencies
      shell: "export PYCURL_SSL_LIBRARY=openssl && ~/.local/bin/pipenv install --python 3.6"
      args:
        chdir: hattrick/

    - name: install the Ansible roles from galaxy
      shell: "~/.local/bin/pipenv run ansible-galaxy install -r playbooks/requirements.yml"
      args:
        chdir: hattrick/

    - name: Copy vars example file
      copy:
        src: hattrick/vars/vars.example.yml
        dest: hattrick/vars/vars.yml
        remote_src: yes

    - debug:
        msg:
         - "On RHEL 7, you need ~/.local/bin in your path to make the pipenv command available"
         - "Run the following to add pipenv command to your path"
         - "$ source .bash_profile"
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"
