---
- hosts: localhost
  tasks:
    - name: Provision CloudForms appliances
      include_role:
        name: cloudforms
        tasks_from: provision_openstack

    - name: Refresh inventory to discover CloudForms Appliances
      meta: refresh_inventory

    - name: show all the hosts
      debug:
        msg: "{{ item }}"
      with_inventory_hostnames:
        - all

#- hosts: cloudforms_db
#  tasks:
#    - name: Configure CloudForms DB
#      include_role:
#        name: cloudforms
#        tasks_from: configure_db

#- hosts: cloudforms_ui
#  tasks:
#    - name: Configure CloudForms UI
#      include_role:
#        name: cloudforms
#        tasks_from: configure_ui

#- hosts: cloudforms_wk
#  tasks:
#    - name: Configure CloudForms Workers
#      include_role:
#        name: cloudforms
#        tasks_from: configure_wk
