---
- hosts: kvm
  gather_facts: no
  tags: provision
  become: true
  vars:
    kvm_vm_hostname: "{{ content_hostname }}"
    kvm_vm_root_pwd: "{{ content_ssh_pwd }}"
    kvm_vm_base_img: "{{ content_base_img }}"
    kvm_vm_vcpus: "{{ content_vcpus }}"
    kvm_vm_ram: "{{ content_ram }}"
    kvm_vm_os_disk_name: "{{ content_os_disk_name }}"
    kvm_vm_os_disk_size: "{{ content_os_disk_size }}"
    kvm_vm_nics: "{{ content_nics }}"
  tasks:
    - name: Provision RH content server VM
      include_role:
        name: RedHatGov.kvm_vm

    - name: Add Content to ansible inventory
      add_host:
        name: "{{ content_hostname }}"
        ansible_host: "{{ content_public_ip }}"
        rhsm_consumer_name: "{{ content_hostname }}.{{ domain }}"
      changed_when: no

    - name: waiting for content server ssh to come online
      wait_for:
        host: "{{ content_public_ip }}"
        port: 22
        state: started
        delay: 10
        connect_timeout: 300
        sleep: 5

- hosts: content
  tasks:
    - name: Register to RHSM
      vars:
        rhsm_consumer_name: "{{ content_hostname }}.{{ domain }}"
        rhsm_repos: "{{ content_repos }}"
      include_role:
        name: RedHatGov.rhsm

    - name: Install and configure content server
      include_role:
        name: RedHatGov.content
      tags: install, configure, registry, repos, nfs
