---
- hosts: kvm
  gather_facts: no
  tags: provision
  become: true
  vars:
    kvm_vm_hostname: "{{ director_hostname }}"
    kvm_vm_root_pwd: "{{ director_ssh_pwd }}"
    kvm_vm_base_img: "{{ director_base_img }}"
    kvm_vm_vcpus: "{{ director_vcpus }}"
    kvm_vm_ram: "{{ director_ram }}"
    kvm_vm_os_disk_name: "{{ director_os_disk_name }}"
    kvm_vm_os_disk_size: "{{ director_os_disk_size }}"
    kvm_vm_nics: "{{ director_nics }}"
  tasks:
    - name: Provision RHOSP Director VM
      include_role:
        name: RedHatGov.kvm_vm

    - name: Add Content to ansible inventory
      add_host:
        name: "{{ director_hostname }}"
        ansible_host: "{{ director_public_ip }}"
        rhsm_consumer_name: "{{ director_hostname }}.{{ domain }}"
      changed_when: no

    - name: waiting for content server ssh to come online
      wait_for:
        host: "{{ director_public_ip }}"
        port: 22
        state: started
        delay: 10
        connect_timeout: 300
        sleep: 5

- hosts: director
  tags: install
  tasks:
    - name: Register to RHSM
      vars:
        rhsm_consumer_name: "{{ director_hostname }}.{{ domain }}"
        rhsm_repos: "{{ director_repos }}"
      include_role:
        name: RedHatGov.rhsm
      tags: install

    - name: Install Director
      include_role:
        name: director
      tags: install

    - name: Configure Director
      include_role:
        name: director
        tasks_from: post_config
      tags: configure

    - name: Register Overcloud Nodes
      include_role:
        name: director
        tasks_from: register_overcloud_nodes
      tags: register
