---
- name: Play to copy local pub key to kvm host
  hosts: kvm
  gather_facts: no
  roles:
    - copy_local_pub_key

- name: Play to deploy kvm host
  hosts: kvm
  tasks:
    - name: Register to RHSM
      vars:
        rhsm_consumer_name: "{{ kvm_hostname_full }}"
        rhsm_repos: "{{ kvm_repos }}"
      include_role:
        name: ansible-rhsm

    - name: Deploy kvm
      include_role:
        name: kvm

    - name: fetch public key from KVM host for use later
      fetch:
        src: /root/.ssh/id_rsa.pub
        dest: "{{ playbook_dir }}/files/kvm_root_id_rsa.pub"
        flat: yes
