---

- hosts: localhost
  tasks:
    - name: Provision OpenShift infrastructure
      include_role:
        name: openshift
        tasks_from: provision_openstack

    - name: Refresh inventory to discover OpenShift infrastructure
      meta: refresh_inventory

- hosts: openshift_nodes
  tasks:
    - name: Prepare OpenShift nodes
      include_role:
        name: openshift
        tasks_from: prerequisites

- hosts: openshift_master
  tasks:
    - name: Provision OpenShift infrastructure
      include_role:
        name: openshift
