---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Add keypair with current user public key
    os_keypair:
      auth: "{{ os_auth }}"
      state: present
      name: hattrick_user
      public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  - name: Create Tower instance
    include_role:
      name: openstack_instance
    vars:
      os_instance_name: "{{ tower_hostname }}.{{ domain }}"
      os_instance_image: rhel75
      os_instance_flavor: m1.large
      os_instance_key_name: hattrick_user
      os_instance_network: private
      os_instance_auto_ip: no
      os_instance_terminate_volume: yes
      os_instance_security_groups:
        - name: ssh
          description: Allow SSH
          rules:
            - protocol: tcp
              port_range_min: 22
              port_range_max: 22
              remote_ip_prefix: 0.0.0.0/0
        - name: web
          rules:
            - protocol: tcp
              port_range_min: 443
              port_range_max: 443
              remote_ip_prefix: 0.0.0.0/0
      os_auth: "{{ os_auth }}"

  - name: Assign floating IP to Tower
    os_floating_ip:
      auth: "{{ os_auth }}"
      state: present
      server: "{{ tower_hostname }}.{{ domain }}"
      nat_destination: private
      floating_ip_address: "{{ tower_public_ip }}"
      reuse: true
      wait: true

  - name: Wait for instance become ready to use
    wait_for:
     host: "{{ tower_public_ip }}"
     port: "22"
     timeout: "320"
     state: "started"

  - name: Pause playbook execution for 30 seconds
    pause:
      seconds: 30

  - name: Refresh inventory to discover Tower instance
    meta: refresh_inventory

- hosts: tower
  tasks:
  - name: Register to RHSM
    vars:
      rhsm_consumer_name: "{{ tower_hostname }}.{{ domain }}"
      rhsm_repos: "{{ tower_repos }}"
    include_role:
      name: RedHatGov.rhsm
    tags: install

  - name: Install Tower
    include_role:
      name: tower
    tags: install
