---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Provision Tower
    vars:
      os_auth: "{{ general_os_auth }}"
    include_role:
      name: tower
      tasks_from: provision_openstack
    tags: provision

  - name: Refresh inventory to discover Tower instance
    meta: refresh_inventory
    tags: provision

- hosts: tower
  tasks:
  - name: Register to RHSM
    vars:
      rhsm_consumer_name: "{{ tower_hostname }}.{{ domain }}"
      rhsm_repos: "{{ tower_repos }}"
    include_role:
      name: RedHatGov.rhsm
    tags: install

  - name: Install Tower
    include_role:
      name: tower
    tags: install
