---
# defaults file for idm
idm_hostname: [] #Short hostname only
idm_ssh_user: root
idm_ssh_pwd: p@ssw0rd
idm_public_ip: []
idm_base_img: []
idm_vcpus: 1
idm_ram: 4096 #In Megabytes
idm_os_disk_name: []
idm_os_disk_size: 45G
idm_nics:
  - name: eth0
    bootproto: static
    onboot: yes
    ip: []
    prefix: []
    gateway: []
    dns_server: []
    config: "--type network --source default --model virtio"
idm_realm: []
idm_dm_pwd: []
idm_admin_pwd: []
#NOTE: if disconnected installation, do not provide forward_ip
idm_forward_ip: []
idm_reverse_zone: []
idm_repos:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
idm_packages:
    - ipa-server
    - ipa-server-dns
idm_users: []
idm_dns_records: []
